// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// rcpp_hru
void rcpp_hru(NumericVector dem, IntegerVector hillslope_id, IntegerVector channel_id, NumericVector land_area, NumericVector channel_area, NumericVector grad, NumericVector atb, arma::sp_mat W, NumericVector area, NumericVector s_bar, NumericVector atb_bar, NumericVector rst_prop);
RcppExport SEXP _dynatopGIS_rcpp_hru(SEXP demSEXP, SEXP hillslope_idSEXP, SEXP channel_idSEXP, SEXP land_areaSEXP, SEXP channel_areaSEXP, SEXP gradSEXP, SEXP atbSEXP, SEXP WSEXP, SEXP areaSEXP, SEXP s_barSEXP, SEXP atb_barSEXP, SEXP rst_propSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type dem(demSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type hillslope_id(hillslope_idSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type channel_id(channel_idSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type land_area(land_areaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type channel_area(channel_areaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type grad(gradSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type atb(atbSEXP);
    Rcpp::traits::input_parameter< arma::sp_mat >::type W(WSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type area(areaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type s_bar(s_barSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type atb_bar(atb_barSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type rst_prop(rst_propSEXP);
    rcpp_hru(dem, hillslope_id, channel_id, land_area, channel_area, grad, atb, W, area, s_bar, atb_bar, rst_prop);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_dynatopGIS_rcpp_hru", (DL_FUNC) &_dynatopGIS_rcpp_hru, 12},
    {NULL, NULL, 0}
};

RcppExport void R_init_dynatopGIS(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
