// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// fun_downslope_pass
List fun_downslope_pass(NumericVector dem, IntegerVector order, IntegerVector seq, IntegerVector offset, NumericVector area, NumericVector dx, NumericVector cl);
RcppExport SEXP _dynatopGIS_fun_downslope_pass(SEXP demSEXP, SEXP orderSEXP, SEXP seqSEXP, SEXP offsetSEXP, SEXP areaSEXP, SEXP dxSEXP, SEXP clSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type dem(demSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type order(orderSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type seq(seqSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type area(areaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type dx(dxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cl(clSEXP);
    rcpp_result_gen = Rcpp::wrap(fun_downslope_pass(dem, order, seq, offset, area, dx, cl));
    return rcpp_result_gen;
END_RCPP
}
// fun_upslope_pass
List fun_upslope_pass(NumericVector dem, IntegerVector order, IntegerVector offset);
RcppExport SEXP _dynatopGIS_fun_upslope_pass(SEXP demSEXP, SEXP orderSEXP, SEXP offsetSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type dem(demSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type order(orderSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type offset(offsetSEXP);
    rcpp_result_gen = Rcpp::wrap(fun_upslope_pass(dem, order, offset));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_dynatopGIS_fun_downslope_pass", (DL_FUNC) &_dynatopGIS_fun_downslope_pass, 7},
    {"_dynatopGIS_fun_upslope_pass", (DL_FUNC) &_dynatopGIS_fun_upslope_pass, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_dynatopGIS(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
