#' Add a channel to the gis_brick
#'
#' @description Reads the DEM file, sets up the raster brick and saves it
#'
#' @param brck a RasterBrick as created by create_brick
#' @param channel a channel object as generated by create_channel
#'
#' @return a raster brick object as for brck but with additional layers populated
#'
#' @details Populates the channel_id & channel_area layers. Alters the land_area layer to correspond.
#' @export
add_channel <- function(brck,channel){
    
    ## pass to checks
    check_brick(brck)
    check_channel(channel)
    
    ## extract cells index, and fraction of river area in cell
    ch_cell<- raster::extract(brck[['land_area']],channel,weights=TRUE,cellnumbers=TRUE,na.rm=TRUE)

    ## Loop and add the chanel id and channel area
    ch_area <- raster::area(channel) # areas of river channels
    for(ii in 1:length(ch_cell)){
        ch_cell[[ii]] <- data.frame( id = channel[['id']][ii],
                                    land_area = ch_cell[[ii]][,'value'],
                                    channel_area = ch_area[ii]*ch_cell[[ii]][,'weight'],
                                    cell = ch_cell[[ii]][,'cell'],
                                    stringsAsFactors=FALSE)
    }

    ## merge the list
    ch_cell <- do.call(rbind,ch_cell)
    
    ## assign the cells with multiple chanel id to the
    ## one with the largest area in the cell (equals returns first in list)
    ch_cell <- do.call(rbind,
                   lapply(split(ch_cell,ch_cell$cell),
                          function(chunk) chunk[which.max(chunk$channel_area),]))

    ## make land an channel area in ch_cell consistent
    ch_cell[,'channel_area'] <- pmin( ch_cell[,'channel_area'], ch_cell[,'land_area'] )
    ch_cell[,'land_area'] <- ch_cell[,'land_area'] - ch_cell[,'channel_area']

    ## add to rasters and write out
    brck[['land_area']][ch_cell$cell] <- ch_cell$land_area
    brck[['channel_area']][ch_cell$cell] <- ch_cell$channel_area
    brck[['channel_id']][ch_cell$cell]  <- ch_cell$id
        
    return(brck)
}
