#' Burn in distinct classes of hydrological response units (HRUs)
#'
#' @description Burn in distinct regions to a classification map
#'
#' @param stck a raster brick as generated by create_brick
#' @param class_name Name of the existing classification onto which to burn the new classes - must be a layer in stck
#' @param output_name name to give the output layer added to stck
#' @param burns Named list of layer in stck to burn into discretisation of HRUs that will be stamped onto the classification. Overrides any classification already defined
#' @param json_path Path of folder into which to write the json file identifying which burns were used.
#' @param ... passed to \code{raster::stack} if loading a file
#' 
#' @return a raster layer as stck but with additional layer added.
#'
#' @details Create an additional layer in stck with a classification based on class_name with the burns overwriting the original class values. Burns are applied in the order theya are input.
#'
#' @export
burn_in_class <- function(stck,class_name,output_name,burns,json_path=getwd(),...){

    if(!("RasterStack" %in% class(stck))){
        if( is.character(stck) ){
            stck_file <- stck
            stck <- raster::stack(stck,...)
        }else{
            stop("Unknown format for input")
        }
    }else{
        stck_file <- character(0)
    }

    check_catchment(stck)

    ## check burns are valid
    burns <- as.vector(burns)
    burns <- as.character(burns)

    ## check layers exist
    if( !all(c(class_name,burns) %in% names(stck)) ){
        stop("Missing layers used to perform burn")
    }

    ## check output name isn;t already in use
    if( output_name %in% names(stck) ){
        stop("Output name already used")
    }

    ## process in new class
    nc <- stck[[class_name]]
    for(ii in burns){
        idx <- Which(is.finite(stck[[ii]]),cells=TRUE)
        nc[idx] <- stck[[ii]][idx]
    }

    nc <- raster::mask(nc,stck[['dem']])
    names(nc) <- output_name
    stck <- addLayer(stck,nc)

    ## make json
    tmp <- jsonlite::fromJSON( file.path(json_path,paste0(class_name,'.json')), simplifyVector=FALSE )
    tmp$burns <- burns
    writeLines( jsonlite::toJSON(tmp,pretty=TRUE), file.path(json_path,paste0(output_name,'.json')) )


    if(length(stck_file)>0){
        writeRaster(stck,stck_file)
        return(stck_file)
    }else{
        return(stck)
    }

}
