# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' cpp wrapper function for passing up the catchments from river nodes
#' 
#' @param dem Digital elevation model as a vector
#' @param channel_id UID of channel present in the pixel
#' @param land_area Area of land surface in pixel
#' @param offset - difference between cell index of adjacent cells and current cell index - clockwise from top left
#' @param dx distance between cell centres - from top left in clockwise direction
#' @param cl contour length - from top left in a clockwise direction. The 9th value is used for cells split beteen land and channel
#' 
#' @return a list with the filled dem, order, upslope_area, contour_length, gradient and atanb
#'
rcpp_compute_properties <- function(dem, channel_id, land_area, offset, dx, cl) {
    .Call('_dynatopGIS_rcpp_compute_properties', PACKAGE = 'dynatopGIS', dem, channel_id, land_area, offset, dx, cl)
}

#' cpp wrapper function for computation of redistribution matrices
#' 
#' @param dem Digital elevation model
#' @param grad average downslope gradient
#' @param land_area Area of land surface in pixel
#' @param channel_area Area of channel surface in pixel
#' @param channel_id UID of channel present in the pixel
#' @param hillslope_id hillslope class of each pixel
#' @param offset - difference between cell index of adjacent cells and current cell index - clockwise from top left
#' @param dx distance between cell centres - from top left in clockwise direction
#' @param cl contour length - from top left in a clockwise direction. The 9th value is used for cells split beteen land and channel
#' @param max_index maximum value of the hillslope and channel id's
#' @return list of hillslope and channel properties
#'
rcpp_hru <- function(dem, grad, land_area, channel_area, channel_id, hillslope_id, offset, dx, cl, max_index) {
    .Call('_dynatopGIS_rcpp_hru', PACKAGE = 'dynatopGIS', dem, grad, land_area, channel_area, channel_id, hillslope_id, offset, dx, cl, max_index)
}

#' cpp wrapper function for passing up the catchments from river nodes
#' 
#' @param dem Digital elevation model as a vector
#' @param channel_id UID of channel in the pixel (id any) as a vector
#' @param offset difference between index of neighbours and current cell - clockwise from top left
#' 
#' @return a list with the filled dem
#'
fun_sink_fill <- function(dem, channel_id, offset) {
    .Call('_dynatopGIS_fun_sink_fill', PACKAGE = 'dynatopGIS', dem, channel_id, offset)
}

