# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fun_atb <- function(dem, area, is_channel, dist, max_iter) {
    .Call('_dynatopGIS_fun_atb', PACKAGE = 'dynatopGIS', dem, area, is_channel, dist, max_iter)
}

fun_redistribution <- function(dem, land_area, hillslope, channel, number_hillslope_class, number_channel_class, dist) {
    .Call('_dynatopGIS_fun_redistribution', PACKAGE = 'dynatopGIS', dem, land_area, hillslope, channel, number_hillslope_class, number_channel_class, dist)
}

fun_sink_fill <- function(dem, is_channel, delta, max_iter) {
    .Call('_dynatopGIS_fun_sink_fill', PACKAGE = 'dynatopGIS', dem, is_channel, delta, max_iter)
}

fun_tanb <- function(dem, is_channel, dist) {
    .Call('_dynatopGIS_fun_tanb', PACKAGE = 'dynatopGIS', dem, is_channel, dist)
}

fun_upslope_area <- function(dem, area, is_channel, dist, max_iter) {
    .Call('_dynatopGIS_fun_upslope_area', PACKAGE = 'dynatopGIS', dem, area, is_channel, dist, max_iter)
}

