#' Fill the sinks with a dem
#'
#' @description The sink filling algorithm of Planchona and Darboux 2001
#'
#' @param stck a RasterStack object as generated by create_catchment
#' @param min_grad Minimum gradient between cell centres
#' @param max_it maximum number of replacements to trial
#' @param verbose pront out additional diagnostic information
#' @param ... additional variables passed to raster::stack if stck is a file name
#' @return an altered RasterStack object with the filled_dem populated.
#'
#' @details The algorithm implimented in Planchona and Darboux, "A fast, simple and versatile algorithm to fill the depressions in digital elevation models" Catena 46 (2001). A pdf can be found at https://horizon.documentation.ird.fr/exl-doc/pleins_textes/pleins_textes_7/sous_copyright/010031925.pdf.
#'
#' If stck is a character object it is presemed to be the path to a file containing the catchment RasterStack. If so it read in and overwritten with the result using the raster package.
#'
#' @export
sink_fill <- function(stck,min_grad = 1e-4,max_it=1e6,verbose=FALSE,...){
 
    if(!("RasterStack" %in% class(stck))){
        if( is.character(stck) ){
            stck_file <- stck
            stck <- raster::stack(stck,...)
        }else{
            stop("Unknown stck format")
        }
    }else{
        stck_file <- character(0)
    }

    check_catchment(stck)
    
    ## extract dem and channel_id values
    z <- raster::getValues(stck[['dem']])
    ch_id <- raster::getValues(stck[['channel_id']])

    w <- z
    w[!is.na(w)] <- Inf
    w[is.finite(ch_id)] <- z[is.finite(ch_id)]

    ## set minium expected increase
    dx <- mean(raster::res(stck))
    nc <- ncol(stck)
    nr <- nrow(stck)

    idx <- which(!is.na(w))

    something_done <- TRUE
    it <- 1
    while( something_done ){
        if( verbose ){
            print(paste("Iteration",it))
        }
        something_done <- FALSE
        for(ii in idx){
            if( w[ii] > z[ii] ){
                ## then need to investigate
                ## compute neighbours
                jj <- fN(ii,nr,nc,dx)
                w_min <- min(w[jj$idx]+jj$dx*min_grad,na.rm=TRUE)
                if( z[ii] > w_min ){
                    ## set to z and leave
                    w[ii] <- z[ii]
                    something_done <- TRUE
                }else{
                    if( w[ii] > w_min ){
                        w[ii] <- w_min
                        something_done <- TRUE
                    }
                }
            }
        }
        if( it > max_it ){
            warning("Maximum number of iterations reached, sink filling not complete")
            something_done <- FALSE # cause end of while loop
        }
        it <- it+1
        #print(sum(is.finite(w)))
    }

    ## copy filled dem back into stack
    stck <- raster::setValues(stck, w, layer=which(names(stck)=="filled_dem"))

    if(length(stck_file)>0){
        raster::writeRaster(stck,stck_file)
        return(stck_file)
    }else{
        return(stck)
    }
}
